# Generated by Django 4.1.7 on 2023-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCryProject', '0003_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default='0'),
        ),
    ]
